### ISSUE TITLE
Add the s4l-full product on aws-prod and make it available (EPIC)

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#171]
```[tasklist]
- [x] Buy / Use Domain
- [x] Route 53 Records + Mail
- [x] IAM: Add permissions for Route53 DNS Challange to IAM user that ops-traefik uses
- [x] AWS SES / Workmail / Forwards to Z43 mail
- [x] Traefik-Rules
- [x] Add sim4life.io maintenance page
- [x] Modify and design sim4life.io maintenance page  ( delegate once ready to @maiz )
- [x] Add  necessary e2e-ops test (PR: https://git.speag.com/oSparc/e2e-ops/-/merge_requests/60#0c4b5c69e1a9129fdf4631622e99c054dbb9f0cf )
- [x] Add Product to postgres database
- [x] Connect the two AWS accounts in a good / secure way (or validate that they are)
- [x] Check for vCPU vGPU etc. limits and if nec
- [x] Add integration with aws-lambda (on itis aws account) for uptime checking
- [x] Once all is done: Compile a list of things to do for the addition of a new product
```

**Comment by mrnicegyu11** [comment]
please re-assign me once the point `Connect the two AWS accounts in a good / secure way (or validate that they are)` is done, thx

**Comment by mrnicegyu11** [comment]
This is the list of necessary tasks for adding a new product as of today, posting it here for posterity:

- Buy / Use Domain
- Route 53 Records + Mail
- IAM: Add permissions for Route53 DNS Challange to IAM user that ops-traefik uses
- Ensure SSL certificate generation works by setting `CERTIFICATE_GENERATION_FQDNS` (see https://github.com/ITISFoundation/osparc-ops-environments/commit/a06a0892ca1fb3bf6402fec5f61d707b894059f8 )
- AWS SES / Workmail / Forwards to Z43 mail
- Traefik-Rules
- Add product maintenance page to config repository
- Add necessary e2e-ops test (PR: https://git.speag.com/oSparc/e2e-ops/-/merge_requests/60#0c4b5c69e1a9129fdf4631622e99c054dbb9f0cf )
- Add product to postgres database
- Connect the AWS accounts in a good / secure way (or validate that they are, VPC pairing)
- Check for vCPU vGPU etc. limits and increase if neccessary
- Add integration with aws-lambda (on itis aws account) for uptime checking
