### ISSUE TITLE
Make progress on terraform (EPIC)

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#176]
Potential points for progress:

- Add the uptime-checking lambda as a terraform module
- Add staging RDS, S3 bucket, etc. as terraform infrastructure

...
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/258
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/266
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/265
```

**Comment by mrnicegyu11** [comment]
Some done in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/5

**Comment by mrnicegyu11** [comment]
More currently done in follow-up MR https://git.speag.com/kaiser/osparc-ops-deployment-configuration/-/merge_requests/1
