### ISSUE TITLE
Env-Var Cleanup (EPIC)

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#177]
We need to get a better grasp on how and where environment variables are added, modified, defined for deployments. Currently, there are a lot of places that they come in.

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/268
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/224
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/244
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3635
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/404
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/463
```

**Comment by mrnicegyu11** [comment]
my tasks are done, reassigning to YH
