### ISSUE TITLE
Refactor e2e-ops

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#189]
```[tasklist]
### Tasks
- [x] Remove `osparc-metrics`
- [x] Remove all secrets from ansible playbooks in `osparc-infra`
- [x] take credentials in `e2e-ops` from `osparc-ops-deployment-configuration`
  - [ ] also pgbackup and mail-server e2e-ops-test
  - [ ] and also github access token
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/638
- [ ] use pytest everywhere
```

**Comment by mrnicegyu11** [comment]
@YuryHrytsuk is currently refactoring the interconenction and design of the `osparc-ops-deployment-configuration` repo, touching `osparc-infra` as well. His plan might be different from what was laid out above. I will assign YH for now.

**Comment by mrnicegyu11** [comment]
done for now
