### ISSUE TITLE
Re-Provision `/docker` filesystem as xfs

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#190]
```[tasklist]
### Tasks
- [x] tip01 WONT DO
- [x] tip02 WONT DO
- [x] tip03 WONT DO
- [x] tip04 WONT DO
- [x] aws-staging
- [x] aws-prod
- [x] aws-autoscaled-nodes
- [x] master01
- [x] master02
- [x] master03
- [x] master04
- [x] master05
- [x] master06
- [x] master07
- [ ] dalco01
- [ ] dalco02
- [ ] dalco03
- [ ] dalco04
- [ ] dalco05
- [ ] dalco06
- [ ] dalco07
- [ ] dalco08
- [ ] dalco09
- [ ] dalco10
```

**Comment by YuryHrytsuk** [comment]
WON'T FIX. Not relevent anymore
