### ISSUE TITLE
Security: Autoscaled EC2 instances currently need to be accessible through the internet

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#195]
Moved from gitlab, original message from @sanderegg:
```
In the current implementation, it is not possible to start an EC2 instance for autoscaling without making it available through the internet.
This is security wise a problem, as anyone with the IP and ssh may be able to connect on the machine.
Currently it is necessary for the machine to be Internet accessible due to the following facts:
- need to ssh on the machine for debugging purposes
- the machine needs to access Dockerhub to pull images

Please devise what should be done there. [@kaiser](https://github.com/kaiser) talked about having some kind of router.
Take your time to find out, but I do think it would be desirable before we unleash sim4life full
```
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5882#pullrequestreview-2082140345
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/682
- [x] ops: change master infra
- [x] ops: change staging infra [STAG Release]
- [ ] ops: change prod infra [PROD Release]
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5883
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/683
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5886
```

**Comment by YuryHrytsuk** [comment]
- [ ] master ([PR](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/607/diffs#abe91a13e644304bd01ecf4ecbeaae158c54b241))
- [ ] stag
- [ ] prod

**Comment by YuryHrytsuk** [comment]
Waiting for PROD release

**Comment by YuryHrytsuk** [comment]
This PR https://github.com/ITISFoundation/osparc-ops-environments/issues/195 tracks this issue
