### ISSUE TITLE
EPIC: Maintenance pages

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#206]
To have a maintenance page even if the docker swarm is down or machines are down, a machine hosting the nginx-based maintenance page needs to be added to the load-balancing.

On aws:
- Add a dedicated ultra-small machine, or even better, a lambda, which only shows the maintenance page. This is added to the `osparc.io` and `staging.osparc.io` loadbalancer. 

On dalco:
- Request a VM, or if impossible, a shitty old machine
- Provision with keepalived (as found in osparc-infra/ansible) to share the Floating IP
- Have it run only the maintenance page

On master:
- We dont need it for now

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/325
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/214
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/218
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/409
- [x] Add FloatingIP maintenance page for dalco with VM from O+P
- [x] Audit ansible provisioning of maintenance VM machines
```

**Comment by YuryHrytsuk** [comment]
This is done for NIH / DALCO / TIP / Sim4life PROD
