### ISSUE TITLE
define migration of service specs overriding for power users

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops-environments#256]
Once the referenced issue reaches production we should remove the special service overrides from the database.

Instead of having every single instance starting with the overriden resources, now it is persisted with the project.

Since there are projects already out that require these increased resources they need to be migrated.

proposed steps to follow:
1. list the projects which use services that require these increased resources
2. for each of them, either change the resource directly in the UI (this will auto-migrate the resource to the project nodes persistency system)
3. Once done, remove the resource override in services_specifications table for the group (be careful to only remove the resources changes, keep anything else such as service placement)
```[tasklist]
### Tasks
- [ ] List the projects that need overriden resources
- [ ] For each of the project, open the project and adjust the node resources in oSparc UI
- [ ] Remove the resource override in services_specifications table
```

**Comment by mrnicegyu11** [comment]
@sanderegg does this still apply and are you still "doing" it, since you are assinged
