### ISSUE TITLE
Import aws-staging items into terraform state

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#265]
Some progress in
- https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/5

#### not done
- [ ] AMI Image creation (find README.md)
- [ ] VPC Peering (write a nice README.md)

```[tasklist]
### Tasks
- [x] https://git.speag.com/kaiser/osparc-ops-deployment-configuration/-/merge_requests/1
- [x] https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/jobs/3155876
- [x] Route 53 for domain
- [x] Bastion-Host
- [x] SES (Workmail) [doesnt apply on aws-staging atm]
```

**Comment by mrnicegyu11** [comment]
Done from CI run https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/jobs/3155876 onwards

**Comment by mrnicegyu11** [comment]
done for now
