### ISSUE TITLE
Make Progress on Z43 Energy Page

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#267]
PO Ticket: https://github.com/ITISFoundation/osparc-issues/issues/976
```[tasklist]
### Tasks
- [x] Enable running the code on a local machine (currently development is only possible on the production VM)
- [x] Improve code quality: typing, linting, pre-commit
- [x] Dockerize the microservices of the energy page
- [x] Fix CI testing
- [x] Add further (unit) testing
- [x] Refactor code: Make functional units smaller, introduce clear data processing pipeline, descriptive variable names
- [x] Investigate: VM sometimes runs at 100% CPU Load constantly
- [x] Refactor "testing / staging" version of the energy page, push latest changes (datepicker etc.) to "main" version of energy page
- [ ] Introduce backups of data
```
