### ISSUE TITLE
Fix Dollar Sign Escape in Env-Var in Invitation service on aws-production

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#274]
There is a problem with special characters in the invitation service. Therefore it had to be changed manually in the production. @mrnicegyu11  @matusdrobuliak66 has more information. 
```[tasklist]
### Tasks
- [x] BUG: Invitations system is at the moment not working. Fixed by: https://github.com/ITISFoundation/osparc-ops-environments/pull/281
- [x] INVITATIONS_OSPARC_URL must be https://s4l-lite.io/
- [x] Change the password in sync with O+P to not contain special characters
- [x] Should be able to test creation of invitations via https://invitations.s4l-lite.io/dev/doc#/invitations/create_invitation_v1_invitations_post
- [x] Create e2e in ops that test this feature (i.e. creates an invitation) Optional: Check that no special chars are used.
```

**Comment by mrnicegyu11** [comment]
The invitation creation can be tested using `curl` by
```
password='passwordWithSpecialChars'
encodedPassword=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$password'''))")
curl https://scu:$encodedPassword@invitations.s4l-lite.io/v1/invitations -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data-raw $'{\n  "issuer": "issuerid",\n  "guest": "invitedguest@company.com",\n  "trial_account_days": 2\n}'
```

**Comment by YuryHrytsuk** [comment]
The invitations url is fixed in the PR below:

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/16

**Comment by YuryHrytsuk** [comment]
My proposal is to disallow certain characters in password to avoid problems in future. `$` character in env seems to be an overall problem in docker-compose according to [this issue](https://github.com/docker/compose/issues/8607).

I would propose to disallow `$`, `/`, `\`, `:`

**Comment by YuryHrytsuk** [comment]
> My proposal is to disallow certain characters in password to avoid problems in future. `$` character in env seems to be an overall problem in docker-compose according to [this issue](https://github.com/docker/compose/issues/8607).
> 
> I would propose to disallow `$`, `/`, `\`, `:`

 I successfully verified that `docker compose` and `docker compose config` do not properly handle `$` in env variables. So, we need to avoid `$` and potentially other special characters `\`, `/` in env variables.

**Comment by matusdrobuliak66** [comment]
> > My proposal is to disallow certain characters in password to avoid problems in future. `$` character in env seems to be an overall problem in docker-compose according to [this issue](https://github.com/docker/compose/issues/8607).
> > I would propose to disallow `$`, `/`, `\`, `:`
> 
> I successfully verified that `docker compose` and `docker compose config` do not properly handle `$` in env variables. So, we need to avoid `$` and potentially other special characters `\`, `/` in env variables.

Cool thanks! then we need to contact the client so they change the password.

**Comment by YuryHrytsuk** [comment]
The password has been changed in sync with O+P. Thanks to @mrnicegyu11 :tada:

**Comment by YuryHrytsuk** [comment]
The test for invitations credentials has been created. Check it our here:
* https://git.speag.com/oSparc/e2e-ops/-/merge_requests/68
* https://git.speag.com/oSparc/e2e-ops/-/merge_requests/66

**Comment by YuryHrytsuk** [comment]
Everything is done
