### ISSUE TITLE
Add s4l-academia products

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#376]
- [x] master
- [x] zmt-prod

aws-staging:

- [x] staging.sim4life.cloud
- [x] hpc.staging.sim4life.cloud
- [x] science.staging.sim4life.cloud
- [x] hpc-science.staging.sim4life.cloud
