### ISSUE TITLE
Create network tests to detect Dalco network issue from Sept. 2023

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#379]
```[tasklist]
### Tasks
- [x] Test floating IP is listening on basic ports
- [x] Test dalco and dalco staging domains are resolved
- [x] Test monitoring domain is resolved
```
