### ISSUE TITLE
Deployments field tests before the [big] release

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#505]
**Actions**
- [X] simcore traefik --> increase replicas
- [x] make revision on manager EC2 machines

**Tests**
- [x] crucial manager --> put down and test
- [x] simcore node --> put down and test

**OPS tests**
- [x] make sure that postgres backup apply works
- [x] make sure aws snapshot apply works

**To observe**
- [X] What happens if Rabbit is 10 minutes down
- [X] What happens if Postgres is 10 minutes down
- [X] What happens if Redis is 10 minutes down

**Insights**
* director-v2 --> not restartable
* director-v2 --> one instance
* storage --> one instance

@mrnicegyu11 @sanderegg @matusdrobuliak66

**Comment by YuryHrytsuk** [comment]
The tests are scheduled for Mon (Jan. 29) from 8:00 AM till 12:00 PM

**Comment by matusdrobuliak66** [comment]
Idea:
* Keep a spare fully prepared node in the lcuster(in drain mode), so that when one node breaks, we can swiftly introduce a healthy node

**Comment by YuryHrytsuk** [comment]
Observations:
* When Redis is down, we return 404 (webserver is down)

**Comment by YuryHrytsuk** [comment]
### Test Simcore Node is down

**Preparation**
1) Prepare AWS Instance (with Simcore AWS Instance settings / parameters + Ansible) 
2) Stop working Simcore Instance in AWS GUI
3) Add new / fresh Simcore Instance to the swarm and configure docker node labels
4) Observe system

**Comment by YuryHrytsuk** [comment]
## Things to consider to increase platform robustness and recoverability
1. Shall `simcore` node have only `simcore` label and run services that can easily move to another node
2. AWS LB healthcheck mechanism will consider node unhealthy in >1.5 min. Isn't it too long?
    - Reconsider AWS LB Target Group healthcheck settings

**Comment by YuryHrytsuk** [comment]
## Things to consider to increase platform robustness and recoverability
1. Shall `simcore` node have only `simcore` label and run services that can easily move to another node
2. AWS LB healthcheck mechanism will consider node unhealthy in >1.5 min. Isn't it too long?
    - Reconsider AWS LB Target Group healthcheck settings

**Comment by YuryHrytsuk** [comment]
AWS Snapshop [postgres] restore:
* it works
* while restoring, you need to provide all the settings of the NEW RDS instance that you want to restore the snapshot to
    - apparently, there is no way to restore the snapshop into existing database (https://stackoverflow.com/a/24279273)
