### ISSUE TITLE
Move appmotion DB to RDS

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#554]
```[tasklist]
### Tasks (add to)
- [x] aws master
- [x] NIH STAG (wait for staging_TomBombadil3)
- [x] sim4life prod (wait release v1.76.0)
- [x] aws tip (wait release v1.76.0)
- [x] Remove from NIH PROD (wait release v1.76.0)
```

Estimated costs for small or micro t3 instance with <5Gb storage
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/8209087/fb1ee397-7065-4200-abc2-7420d6eeaaaa)

**Comment by YuryHrytsuk** [comment]
ToDo in:
- [ ] master
- [ ] staging
- [ ] prod

**Comment by mrnicegyu11** [comment]
Unlocks https://github.com/ITISFoundation/osparc-ops-environments/issues/549

**Comment by YuryHrytsuk** [comment]
Blocked by https://github.com/ITISFoundation/osparc-simcore/issues/6086 and then https://github.com/ITISFoundation/osparc-simcore/issues/6046

**Comment by YuryHrytsuk** [comment]
Closes https://github.com/ITISFoundation/osparc-ops-environments/issues/549
