### ISSUE TITLE
Docker Swarm Network collisions

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#570]
### ToDo
Properly define docker default address pools we use in daemon.json, in `docker swarm cluster --init` CLI and subnets we explicitly define (e.g. for `inretactive_services_subnet`).

### Literature
* https://stackoverflow.com/questions/51404544/docker-containers-in-stacks-within-ec2-instance-do-not-inherit-dns-nameserver -- EC2 ips collide with Default Docker Network IPs
* https://github.com/moby/moby/issues/43128 -- docker swarm ignore `daemon.json` `default-address-pools`
* https://github.com/docker/docs/issues/8663 -- default address pool vs default address poolS
* https://straz.to/2021-09-08-docker-address-pools/ -- good to understand docker networks

### Insights
* Docker swarm ignores `daemon.json` and only uses CLI option in `docker swarm init` command
* Docker compose relies on `daemon.json`
* By default address pools intersect with IPs of EC2 which leads to problems with DNS and unpredictable networks problems

**Comment by YuryHrytsuk** [comment]
### Current understanding
We need to override default / vanilla address pools for docker swarm. This seems to be only supported via `CLI` option but not via `daemon.json` ([doc excerpt](https://docs.docker.com/engine/swarm/swarm-mode/#configuring-default-address-pools)).

**Comment by YuryHrytsuk** [comment]
https://docs.docker.com/engine/swarm/networking/ -- docker swarm networking concepts

**Comment by YuryHrytsuk** [comment]
### Insights

```bash
cat /etc/docker/daemon.json 
{
  "default-address-pools": [
    {
      "base": "192.168.50.0/29",
      "size": 29
    },
    {
      "base": "192.168.50.8/29",
      "size": 29
    }
  ],
  "debug": true
}
```

`"default-address-pools"` in `daemon.json` defines the subnet of `bridge` docker network (created on every machine). It also defines subnet of `docker_gwbridge` created on `docker swarm init` command.

---

**Comment by YuryHrytsuk** [comment]
settings that need to be configured:
* `default-addr-pools` section in `daemon.json`
* `--default-addr-pool` CLI option for `docker swarm init`

**Comment by YuryHrytsuk** [comment]
ToDo before closing this issue:
- [ ] introduce network configs
  - [ ] master
  - [ ] staging
  - [ ] prod
- [ ] update ansible scripts to use network configs
- [ ] remove hardcoded networks created anywhere outside ansible scripts

**Comment by mrnicegyu11** [comment]
FYI This issue might also be due to network collisions https://git.speag.com/oSparc/osparc-infra/-/issues/incident/39

**Comment by YuryHrytsuk** [comment]
It is done
