### ISSUE TITLE
Private EC2

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#574]
Currently, our EC2 instances are publicly available.

1. Create Private Subnets: Move our Docker Swarm nodes to private subnets. Private subnets don't have a route to the internet by default and their instances can't be accessed directly from the internet.
2. Set Up NAT Gateway: Create a NAT Gateway in a public subnet. This NAT Gateway allows instances in the private subnet to initiate outbound connections to the internet while hiding their private IP addresses.
3. Update Route Tables: Update the route tables of your private subnets to route outbound traffic to the NAT Gateway.
4. Security Group Configuration: Ensure that your security groups only allow necessary inbound and outbound traffic. For example, you might allow inbound traffic only from specific IP addresses or subnets that need to access your services.

By setting up the Docker Swarm nodes in private subnets and routing their outbound traffic through a NAT Gateway, we effectively hide them from direct access from the internet. This setup adds an additional layer of security to our infrastructure.

```[tasklist]
### Done in stages
- [x] Master --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/664
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/782
- [x] [Prod] AWS TIP --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/674#e7d14d429f898757a423156de0e8c49d75240694
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/900
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/822
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/961
```

**Comment by mrnicegyu11** [comment]
connected to https://github.com/ITISFoundation/osparc-ops-environments/issues/195

**Comment by YuryHrytsuk** [comment]
## Private docker swarm cluster machines

It seems that managers have to be on a public subnet. We can still have worker nodes private though 

> Before you begin, ensure that the virtual private cloud (VPC) for your load balancer has at least one public subnet in each Availability Zone where you have targets.

source: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-network-load-balancer.html

> The instances need to be on a public subnet with their default route pointing to the Internet Gateway in order to work with an outside-facing NLB

source: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-network-load-balancer.html

**Comment by YuryHrytsuk** [comment]
### Progress

- [ ] Make sure AWS NLB + private EC2 setup is feasible
- [ ] Configure ansible to work with Bastion host
- [ ] Prepare terraform
- [ ] Migrate data

**Comment by YuryHrytsuk** [comment]
Blocked by https://github.com/ITISFoundation/osparc-ops-environments/issues/716

**Comment by YuryHrytsuk** [comment]
Also blocked by https://github.com/ITISFoundation/osparc-ops-environments/issues/718
