### ISSUE TITLE
Add tip.science dedicated deployment on aws-zmt

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#631]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/642
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/643
- [x] Add tip.science to credentials page
- [x] Allow running on different region than us-east-1
- [x] Add statuspage
```

**Comment by YuryHrytsuk** [comment]
All done

**Comment by YuryHrytsuk** [comment]
Reopen. I should add status page

**Comment by YuryHrytsuk** [comment]
All done
