### ISSUE TITLE
Add and start tip.science deployment

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#643]
It shall preferably live on us-west-1, or if some AWS features are missing on us-east-2

YH: the region is `us-west-2` :warning:

```[tasklist]
### Tasks
- [x] terraform files YH
- [x] repo.config/assets YH
- [x] CI/CD pipeline YH
- [x] Mail-Server (Workmail, SMTP) YH
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5667
- [x] Fix messed `}}` in docker config (create simcore stack) @YuryHrytsuk --> requires later simcore commit sha YH
- [x] AWS SES high recommendation (MAIL_FROM is not set up) [optional / NOT blocking] @YuryHrytsuk
- [x] Graylog is not receiving logs YH
- [x] Update maintenance html YH
- [x] Fix filestash (`S3_SECURE` env var problem) YH
- [x] Verify email workflow works YH
```

**Comment by YuryHrytsuk** [comment]
Add terraform PR:
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/519

**Comment by YuryHrytsuk** [comment]
Problems:
- [ ] storage & clusters-keeper doesn't properly support any region except `us-east1` @sanderegg 
- [ ] `create_simcore_plan` messes `}}` (docker config issues) @YuryHrytsuk 
- [ ] [minor] aws ses identity recommendation (mail_from is not set up properly) @YuryHrytsuk

**Comment by YuryHrytsuk** [comment]
All done. Closing
