### ISSUE TITLE
✨ Enable tip.science v1 and v2 dynamic and comp autoscaling

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#645]
Blocked until 
- https://github.com/ITISFoundation/osparc-ops-environments/issues/631
- https://github.com/ITISFoundation/osparc-ops-environments/issues/632
is done.
```[tasklist]
### Tasks
- [x] Modify osparc-config to include tip as AWS deployment @sanderegg
- [x] Copy current AMIs in us-west-2 @sanderegg
- [x] setup repo.config for autoscaling/clusters-keeper @sanderegg
- [x] adapted autoscaling AMI script to automatically copy to all necessary AWS regions @sanderegg
- [x] Create AMIs (Hard-drive requirements, EC2 machine types, AWS region)
- [x] setup DB for computational autoscaling @sanderegg
- [x] setup DB for dynamic autoscaling @sanderegg
- [x] Fixed S3 issues in simcore @sanderegg
```

**Comment by mrnicegyu11** [comment]
Marking this case as done (restructuring our issues), what remains to be done is : https://github.com/ITISFoundation/osparc-ops-environments/issues/632
