### ISSUE TITLE
Kubernetes: run `adminer` on a cloud machine via k8s.

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#669]
Task: Run `adminer` on a cloud machine via k8s.

_Originally posted by @mrnicegyu11 in https://github.com/ITISFoundation/osparc-ops-environments/issues/618#issuecomment-2107409220_
            

```[tasklist]
### Tasks
- [x] Install k8s cluster with kubespray
- [x] Run k8s locally
- [x] Expose adminer through NodePort (locally)
- [x] Run traefik + expose dashboard (locally)
- [x] Expose adminer through traefik (locally)
- [x] Find a solution to properly expose traefik on clusters ([SO question](https://stackoverflow.com/questions/78522036/how-to-use-kubernetes-with-existing-aws-nlb))
- [x] Run traefik + adminer on a real k8s cluster in cloud
- [x] Configure cert management
- [x] Write minimal deploy CI to use
- [x] Switch to k8s adminer
```

**Comment by YuryHrytsuk** [comment]
### Literature / Sources

How to implement ENV ingestion with helm? 
* https://stackoverflow.com/questions/49928819/how-to-pull-environment-variables-with-helm-charts
* https://stackoverflow.com/a/60098256 (makes sense but does not utilize k8s secrets)

**Comment by YuryHrytsuk** [comment]
### Questions

* shall we 
  - install chars as repos (i.e. `helm repo add <repo-name> && helm install <chart-name> <repo-name>` 
  - **or** we install it form file system (i.e. `helm install <chart-name> `./mychart`)

**Comment by YuryHrytsuk** [comment]
### Ingress vs. LoadBalancer vs. NodePort

An Ingress does not expose arbitrary ports or protocols. Exposing services other than HTTP and HTTPS to the internet typically uses a service of type [Service.Type=NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) or [Service.Type=LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer). (source: https://kubernetes.io/docs/concepts/services-networking/ingress/)
