### ISSUE TITLE
Make cloud deployments secure

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#670]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/574
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/269
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/195
```
