### ISSUE TITLE
Kubernetes enhancements

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#688]
### Tasks
- [ ] [traefik] Break down unwieldy `extraObjects` value in multiple easy-to-manage separate parts (e.g. follow a subchart approach) OPTIONAL
- [x] [traefik] Introduce ip_allowlist middleware
- [ ] [traefik] Use common port for http --> https redirect
- [x] https://github.com/ITISFoundation/osparc-ops-environments/issues/696
- [x] helmfile apply fails when nothing is installed ([cert-manager CRDs issue](https://github.com/cert-manager/cert-manager/issues/7096) and traefik crds issue)
- [x] Introduce Portainer (or similar tool)
- [ ] Detect when service cannot start. Now we are blind and will not notice if sth fails to start
- [x] https://github.com/ITISFoundation/osparc-ops-environments/issues/805
- [ ] CI clone repos job for Kubernetes cluster
- [ ] make `helmfile-diff` fails if nothing is installed (error coming from traefik chart)
- [ ] configure ssh and users on machines
