### ISSUE TITLE
Ensure docker swarm cluster state from config

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#709]
### Current behavior
We do not verify docker swarm configuration explicitly (exception: docker networks). So, we end up in [situation](https://github.com/ITISFoundation/osparc-ops-environments/issues/708) when the `dalco 04` node is commented out in `inventory.ini` but is actually an active node of a running Dalco docker swarm cluster.

### Desired behavior
We verify docker swarm cluster configuration and check that it is in-sync with code (e.g. docker node labels, active nodes)

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/774
- [ ] Ensure Docker Stack state
- [ ] Ensure Docker Service state
- [x] Ensure Network
- [x] ~~Ensure Volumes~~ implicitly tested by having up and running services WONT DO
- [x] ~~Ensure Configs~~ implicitly tested by having up and running services WONT DO
```

**Comment by YuryHrytsuk** [comment]
Possible solution: use docker ansible roles

https://docs.ansible.com/ansible/latest/collections/community/docker/index.html

**Comment by YuryHrytsuk** [comment]
### Docker swarm state
- Cluster state
- Node state
- Stack state
- Service state
- Network
- Volumes
- Configs

**Comment by YuryHrytsuk** [comment]
### Ideal solution
The same process deploying changes is used for monitoring stata (e.g. `terraform plan` and `terraform apply`)
* dry-run option (ideally with diff logs)
* easy to allow failure for parts of it
* used to deploy

**Comment by YuryHrytsuk** [comment]
The only left items are test docker stack and test docker service which is now done implicitly by testing that our services are accessible by URL and that the platform is up and running. This is why it is WONT DO for time being
