### ISSUE TITLE
Refactor osparc-config

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#714]
```[tasklist]
### Tasks
- [x] Fix pre-commit hook
- [x] Add pre-commit to CI
- [x] Unify `.venv` usage
```

**Comment by YuryHrytsuk** [comment]
Blocked until `unification of .venv` is discussed with @mrnicegyu11 and optionally @sanderegg
