### ISSUE TITLE
Fix videostreaming on sim4life.io (and others) - ad-hoc highest prio

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#718]
- Private EC2 machines behind a AWS NAT gateway make the STUN fail. We need to use a **NAT instance (EC2)** instead of a NAT gateway to fix this, see: https://coder.com/docs/networking/stun

```[tasklist]
### Tasks
- [x] Investigate Bug
- [x] Reproduce bug manually
- [x] Push fix to osparc-master-zmt, check videostreaming works
- [x] Add personal machine for Nik to test videostreaming on sim4life.io
- [ ] Do production release with the fix
- [ ] Make terraform states clean again
- [ ] Remove Niks personal machine
- [ ] BONUS: Remove cpu/gpu machine from sim4life.io terraform state and EC2 stopped machines
```
