### ISSUE TITLE
Refactor test_ops_stack test

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#772]
```[tasklist]
### Tasks
- [ ] Avoid hardcode --> use values from repo config
- [ ] Split big file into per-deployment files
- [ ] Update CI and Test to run this logic
```
