### ISSUE TITLE
Ensure Docker Node state

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#774]
```[tasklist]
### Tasks
- [x] all nodes have proper availability
- [x] all nodes have proper labels
- [x] all nodes are registered
- [x] no extra nodes are registered
- [x] all nodes have proper IPs
```

**Comment by YuryHrytsuk** [comment]
https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/803
