### ISSUE TITLE
Consider using grafana terraform provider instead of hacky-DYI-REST-provisioning

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#778]
There is now an official grafana terraform provider with which one can manage alterts, dashboards and the total content of grafana in a stateful way. The changes to the REST API necessary for the major version upgrade to v11 were very very painful, so please Dustin consider next time checking this out first ;)
```[tasklist]
### Tasks
- [x] TF state in S3
- [x] TF state tests
- [x] Automatic makefile tf environment
- [x] Check / Verify: Can one in the GUI easily export dashboards?
- [x] CI/Cd pipeline to auto-import? (or not?)
- [x] Makefile targets j2 templating
```
