### ISSUE TITLE
Kubernetes: multi-node cluster and node-labelled pods

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#805]
Deployment: AWS Master

The Kubernetes cluster shall consist of at least 2 nodes and the pods shall be constrained to particular nodes (e.g. simcore node or ops node like it is done on docker swarm via docker node labels)
```[tasklist]
### Tasks
- [x] Document how to add a new worker node (https://git.speag.com/oSparc/osparc-infra/-/merge_requests/251)
- [x] Document how to update node labels (https://git.speag.com/oSparc/osparc-infra/-/merge_requests/251)
- [x] ~~Assign simcore pods by default to simcore node via common helper chart?~~ WONT DO
- [ ] Add CI Step to configure node labels (https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/964)
- [x] AWS Master: add 2nd node and add node labes (https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/960)
- [x] inhouse master: label k8s node (https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/965)
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/828
```

**Comment by YuryHrytsuk** [comment]
## Useful links
* [kubespray add worker node to the cluster](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/operations/nodes.md#addingreplacing-a-worker-node)
