### ISSUE TITLE
AWS-hosted Redis: clean self-hosted redis

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#807]
```[tasklist]
### Tasks
- [ ] Remove redis from deployments with AWS Redis (label and volume)
- [x] Remove redis-commander label (see comments below)
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/810
- [x] refactored redis-commander: support no user (https://github.com/ITISFoundation/osparc-ops-environments/pull/803)
```

**Remove redis from deployments with AWS Redis (label and volume)**
- [X] Master https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1241
- [X] STAG nothing to do
- [x] PROD  https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1242

**Comment by YuryHrytsuk** [comment]
Related PRs:
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/905
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/906
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/907

**Comment by YuryHrytsuk** [comment]
closes https://github.com/ITISFoundation/osparc-ops-environments/issues/241
