### ISSUE TITLE
Issues during release v1.77.2

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#816]
### Issue during release

```[tasklist]
### Tasks
- [X] Validate Simcore 1 Failed. [Fix commit](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/commit/86f2ae2f65836f2c51f0c6f6d4ffbba18566dfd4). (Shall we have this as a CI test in ./osparc-config) To be discussed with @matusdrobuliak66 
- [X] TCP Router is misconfigured on inhouse tip. [Fix commit](https://github.com/ITISFoundation/osparc-ops-environments/commit/fda0446f038dc19b74c2ade54a2f822bb5942a1c)
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/817
```

### Potential Improvements
* make release tags 1 commands for all deployments (right now we need to run 5 commands [1 per deployment])
* make `terraform-apply` and `terraform-plan`

_Originally posted by @YuryHrytsuk in https://github.com/ITISFoundation/osparc-simcore/issues/6212#issuecomment-2362932744_
