### ISSUE TITLE
Sim4life PROD: private static EC2

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#822]
```[tasklist]
### Tasks
- [ ] Add maintenance ec2 to machine credentials test
- [ ] https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/955
- [ ] https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/955
```

**Comment by YuryHrytsuk** [comment]
PR solving this issue: https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/955

Close once this PR is merged
