### ISSUE TITLE
Cloud Security: Make RDS private

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#832]
```[tasklist]
### Tasks
- [x] [AWS Master](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/977)
- [x] [NIH STAG](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1010)
- [x] [NIH PROD](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1266)
- [x] [SIM4LIFE](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1269)
- [x] [AWS TIP](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1268)
```
---
**Hint**
* Rely on https://repost.aws/knowledge-center/rds-move-to-private-subnet article to make it smooth

**Comment by YuryHrytsuk** [comment]
## Useful resources
* https://blog.networkbits.es/en/posts/2022/ssh_jumphost_restricted_user/
