### ISSUE TITLE
Unify ssh key names

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#861]
```[tasklist]
### Tasks
- [x] prod https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1076
- [x] stag https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/984
- [x] master https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/980
- [x] update `osparc-infra` kubernetes makefile https://git.speag.com/oSparc/osparc-infra/-/merge_requests/260
- [ ] update `syncer` repo
- [x] update kubernetes CI (https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1078)
```
