### ISSUE TITLE
testExtMaintenancePageCurl: does not work with private ec2

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#870]
```[tasklist]
### Tasks
- [x] add reusable code to run tests on remote machines
- [x] support `run once`, `run on managers only` and `run on all nodes` modes
- [x] easy to run locally
```
Implented in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1112
