### ISSUE TITLE
Introduce sim4life lite redirect

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#875]
## Tasks
```[tasklist]
### ToDo
- [x] Test this logic on Master or Staging
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/925
- [x] Add lite redirect ENV https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1194
- [x] Add e2e test https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1193
- [x] Check that redirect works
```

## Potential solution
* ~~use existing dns redirect funcitonality~~ this is not the right solution (read [explanation here](https://blog.nameshield.com/blog/2023/11/30/dns-and-https-redirects-how-do-they-work-together))
* Use AWS LB (does not apply for on-premise deployments)
* Use Traefik redirect (see [forum discussion on implementation](https://community.traefik.io/t/the-best-way-to-implement-global-redirect-to-another-domain-including-any-possible-nested-subdomains-and-paths/25875))

## Related PRs
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/299

## Obesrvations
* both domains represent "secondary" (not "main") product 
* there are no payments enabled for these products
* vendors manual is served under full (non-abbreviated) domain
* invitations service is served under full (non-abbreviated) domain

FYI:
* @mrnicegyu11 
* @mguidon

**Comment by YuryHrytsuk** [comment]
Obesrvations:
* both domains represent "secondary" (not "main") product 
* there are no payments enabled for these products

**Comment by YuryHrytsuk** [comment]
## Resources
- https redirects https://blog.dnsimple.com/2016/08/https-redirects/
-
