### ISSUE TITLE
Ban docker intrusive commands on cluster machines

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#878]
To avoid in future [breaking docker swarm incident](https://git.speag.com/oSparc/osparc-infra/-/issues/57) we should ban [docker] intrusive commands and make sure that these bans work

```[tasklist]
### Tasks
- [x] Add config file to easily append more bash commands to be banned ~~(missing: public05 and public06)~~
- [x] Make sure these changes are applied in PROD
- [x] Regularly SAFEly check that these bans work (YH)(see [PR](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1258))
- [x] Allow user to [easily] disable all blocks in case of emergency when instrusive commands are required
```

**Comment by mrnicegyu11** [comment]
https://git.speag.com/oSparc/osparc-infra/-/merge_requests/265

**Comment by mrnicegyu11** [comment]
done from my side
