### ISSUE TITLE
Expose the `dynamic-scheduler` for usage by platform maintainers

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-ops-environments#892]
To figure out the state of the dynamic services, there is a new dashboard that exports what the `dynamic-scheduler` is keeping track of.

```[tasklist]
### Tasks
- [x] expose the service similarly to what was done for `portioner and co` service must be authenticated
- [x] add an entry to the credentials page where the service can be accessible
- [x] prod https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1183
```

**Comment by mrnicegyu11** [comment]
@GitHK @YuryHrytsuk 

Reopening since the tasklist isnt done, spotted this during the EventHorizon3 release preparations. please remove the tasklist and close again in case it should be so

**Comment by YuryHrytsuk** [comment]
> @GitHK @YuryHrytsuk
> 
> Reopening since the tasklist isnt done, spotted this during the EventHorizon3 release preparations. please remove the tasklist and close again in case it should be so

Thanks. Useful finding :+1: I will follow up on this issue

**Comment by YuryHrytsuk** [comment]
It shall be done after https://github.com/ITISFoundation/osparc-simcore/issues/6728. As long as [Enable dynamic scheduler ui tests](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1183) was merged
