### ISSUE TITLE
NIH PROD: Private Static EC2

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#900]
```[tasklist]
### Tasks
- [x] Make external maintenance private
- [x] Make [non-videostreaming] static docker swarm machines private
- [x] [Enable S3 endpoint](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1051)
- [x] Add maintenance ec2 to e2e tests
- [x] [Remove old machines (except Graylog)](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1220)
- [x] [Remove old machine with graylog](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1233)
```
---
Follow instructions in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1140
