### ISSUE TITLE
Move e2e ops tests to Makefile

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#902]
```[tasklist]
### Tasks
- [ ] tests can be run locally and in CI 
  - [ ] repo.config generation requires DOCKER_IMAGE_TAG on STAG/PROD deployments
- [ ] Run all e2e tests should run only tests relative to the deployment
- [ ] Run all unit / e2e tests should clearly separate which tests are being executed
```
## Related PRs
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1143
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1146
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1148
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1149
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1123
